name: Project Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get install graphviz
          pip install -r requirements.txt
      - name: Run tests
        run: |
          git clone https://github.com/ddomin212/bnb_web.git static/repos/ddomin212/bnb_web
          rm -rf static/repos/ddomin212/bnb_web/tests
      - name: Test with pytest
        run: pytest
        env:
          POE_API_TOKEN: ${{ secrets.POE_API_TOKEN }}